### ISSUE TITLE
bitarray 1.6.2 install fails with No such file or directory: 'bitarray/bitarray.h'

### ISSUE THREAD

**Issue by zaneselvans** [ilanschnell/bitarray#113]
Seems like there might be an issue with the most recent release (v1.6.2)?  I'm getting this installing with pip on Ubuntu using Python 3.8. Both within a virtual environment set up by Tox, and doing `pip install bitarray==1.6.2` within a conda environment.

```
Collecting bitarray>=0.3.4
  Downloading bitarray-1.6.2.tar.gz (55 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/zane/code/catalyst/pudl/.env_pudl/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rv5mn_yq/bitarray_3a44fb1ed8884caead4bfcd1fa2d9e2e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rv5mn_yq/bitarray_3a44fb1ed8884caead4bfcd1fa2d9e2e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8n4oymo_
         cwd: /tmp/pip-install-rv5mn_yq/bitarray_3a44fb1ed8884caead4bfcd1fa2d9e2e/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rv5mn_yq/bitarray_3a44fb1ed8884caead4bfcd1fa2d9e2e/setup.py", line 13, in <module>
        data = open('bitarray/bitarray.h').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'bitarray/bitarray.h'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by DrPyser** [comment]
Also encountering this on a ubuntu-based system.

```
$ uname -a
Linux R90R4K4C 5.4.7-050407-generic #201912311234 SMP Tue Dec 31 17:38:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ pip install bitarray
Collecting bitarray
  Downloading https://files.pythonhosted.org/packages/eb/71/2cb71682facf328d012889e49f7207d248a8e5cf4628d41899c8f256a1a8/bitarray-1.6.2.tar.gz (55kB)
    100% |████████████████████████████████| 61kB 1.1MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-51ir549x/bitarray/setup.py", line 13, in <module>
        data = open('bitarray/bitarray.h').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'bitarray/bitarray.h'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-51ir549x/bitarray/
```

**Comment by ilanschnell** [comment]
Thanks for reporting this problem.  Hmm, inspecting the source tarball on PyPI, I see the `.h` files missing.

**Comment by ilanschnell** [comment]
173c8487ccf6926333d463d8dcaf4b1c82e3e760 show fix the problem.  I'll upload a new release to PyPI soon.

**Comment by ilanschnell** [comment]
I just uploaded bitarray 1.6.3 to PyPI which has includes the `.h` files in the source tarball.  Can you please confirm that the problem is fixed now?  Thanks

**Comment by zaneselvans** [comment]
Appears to be working fine for me now 👍🏼

**Comment by ilanschnell** [comment]
Thanks @zaneselvans !  Can you also confirm that it's working now @DrPyser ?

**Comment by ittqqzz** [comment]
> [173c848](https://github.com/ilanschnell/bitarray/commit/173c8487ccf6926333d463d8dcaf4b1c82e3e760) show fix the problem. I'll upload a new release to PyPI soon.

So far (2021-01-21 11:04:00) the problem remains. Please check it.

**Comment by ilanschnell** [comment]
@ittqqzz what is your system (Python version, OS) and how did you install pip?

**Comment by ittqqzz** [comment]
> @ittqqzz what is your system (Python version, OS) and how did you install pip?


pip script is: pip install -r xxx.txt

i build it in docker, and the log is:
```
#10 72.21 Collecting bitarray>=0.3.4 (from pybloom==1.1->-r deploy/requirements.txt (line 70))
#10 72.66   Downloading http://pypi.garenanow.com/mirror/packages/eb/71/2cb71682facf328d012889e49f7207d248a8e5cf4628d41899c8f256a1a8/bitarray-1.6.2.tar.gz (55kB)
#10 72.89     Complete output from command python setup.py egg_info:
#10 72.89     Traceback (most recent call last):
#10 72.89       File "<string>", line 1, in <module>
#10 72.89       File "/tmp/pip-install-5WKwIu/bitarray/setup.py", line 13, in <module>
#10 72.89         data = open('bitarray/bitarray.h').read()
#10 72.89     IOError: [Errno 2] No such file or directory: 'bitarray/bitarray.h'
#10 72.89     
#10 72.89     ----------------------------------------
#10 73.23 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-5WKwIu/bitarray/
#10    completed: 2021-01-21 02:43:38.061672531 +0000 UTC
```

Python 2.7

OS version Ubuntu 7.4.0-1ubuntu1~16.04~ppa1

gcc version 7.4.0 

btw: when i set bitarray==1.6.1 , problem gone

**Comment by ilanschnell** [comment]
@ittqqzz Thank for the feedback.  I'm wondering if this is some wired caching issue.  Can you try setting `bitarray==1.6.3`?  Thanks

**Comment by ittqqzz** [comment]
> @ittqqzz Thank for the feedback. I'm wondering if this is some wired caching issue. Can you try setting `bitarray==1.6.3`? Thanks

the latest version is ok!
```
Successfully built balabala...
```

**Comment by ilanschnell** [comment]
@ittqqzz Happy to hear!  I've tested `pip install bitarray` on various machines (Linux, OSX, Windows) with different Python versions and found no problems.
